import { createTamagui, createFont, createTokens } from '@tamagui/core'

const font = createFont({
  family: 'System',
  size: {
    true: 16,
    1: 12,
    2: 14,
    3: 16,
    4: 18,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
  },
  weight: {
    true: '400',
    1: '300',
    2: '400',
    3: '500',
    4: '600',
    5: '700',
  },
  letterSpacing: {
    true: 0,
    1: -0.5,
    2: -0.25,
    3: 0,
    4: 0.25,
    5: 0.5,
  },
  lineHeight: {
    true: 1.5,
    1: 1.25,
    2: 1.375,
    3: 1.5,
    4: 1.625,
    5: 1.75,
  },
})

const tokens = createTokens({
  color: {
    color: '#000000',
    color2: '#424242',
    color3: '#757575',
    color4: '#9e9e9e',
    color5: '#bdbdbd',
    background: '#ffffff',
    background2: '#f5f5f5',
    background3: '#eeeeee',
    borderColor: '#e0e0e0',
    primary: '#2196F3',
    secondary: '#9C27B0',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
  },
  space: {
    true: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
  },
  size: {
    true: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
  },
  radius: {
    true: 0,
    1: 4,
    2: 6,
    3: 8,
    4: 10,
    5: 12,
    6: 14,
    7: 16,
    8: 20,
    9: 24,
  },
  zIndex: {
    true: 0,
    1: 100,
    2: 200,
    3: 300,
    4: 400,
    5: 500,
  },
})

const themes = {
  light: {
    color: tokens.color.color,
    color2: tokens.color.color2,
    color3: tokens.color.color3,
    color4: tokens.color.color4,
    color5: tokens.color.color5,
    background: tokens.color.background,
    background2: tokens.color.background2,
    background3: tokens.color.background3,
    borderColor: tokens.color.borderColor,
    primary: tokens.color.primary,
    secondary: tokens.color.secondary,
    success: tokens.color.success,
    warning: tokens.color.warning,
    error: tokens.color.error,
  },
  dark: {
    color: '#ffffff',
    color2: '#bdbdbd',
    color3: '#9e9e9e',
    color4: '#757575',
    color5: '#424242',
    background: '#121212',
    background2: '#1e1e1e',
    background3: '#2c2c2c',
    borderColor: '#424242',
    primary: '#64B5F6',
    secondary: '#BA68C8',
    success: '#81C784',
    warning: '#FFB74D',
    error: '#E57373',
  },
}

export const tamaguiConfig = createTamagui({
  defaultTheme: 'light',
  fonts: {
    body: font,
    heading: font,
  },
  tokens,
  themes,
  shorthands: {
    f: 'flex',
    ai: 'alignItems',
    jc: 'justifyContent',
    fd: 'flexDirection',
    p: 'padding',
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    pt: 'paddingTop',
    pr: 'paddingRight',
    pb: 'paddingBottom',
    pl: 'paddingLeft',
    m: 'margin',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    mt: 'marginTop',
    mr: 'marginRight',
    mb: 'marginBottom',
    ml: 'marginLeft',
    br: 'borderRadius',
    bw: 'borderWidth',
    bc: 'borderColor',
    w: 'width',
    h: 'height',
    c: 'color',
    bg: 'backgroundColor',
    fs: 'fontSize',
    fw: 'fontWeight',
    ta: 'textAlign',
  },
})

export type Conf = typeof tamaguiConfig

declare module '@tamagui/core' {
  interface TamaguiCustomConfig extends Conf {}
}

export default tamaguiConfig
